### ISSUE TITLE
V 1.0 To-Do

### ISSUE THREAD

**Issue by StealtheeEU** [StealtheeEU/Project-17#1]
- [ ]  New Spawn menu using new fonts,
- [ ] Config cleanup following the new framework update,
- [ ] Site integration with database to pull information EG (Player info, vehicle info),
- [ ] Add zipties to current build
- [ ] Add Homeguard Licence (Civilian)
- [ ] Add Homeguard site and spawn,
- [ ] Add Homeguard shops, and keyhandlers,
- [ ] Add 5.0 licence and condition checks to vehicle skins,

<hr>

- [ ] Take from framework 5.0 database changes,
